import "~/styles/globals.css";
import "@uploadthing/react/styles.css"

import { ClerkProvider } from "@clerk/nextjs"
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import React from "react";
import TopNav from "~/app/_components/topnav";
import {NextSSRPlugin} from "@uploadthing/react/next-ssr-plugin";
import {extractRouterConfig} from "uploadthing/server";
import {ourFileRouter} from "~/app/api/uploadthing/core";

export const metadata: Metadata = {
  title: "t3gallery",
  description: "Generated by mee",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
      <ClerkProvider>
        <html lang="en" className={`${GeistSans.variable}`}>
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          <body className="flex flex-col gap-4">
            <TopNav />
          {children}</body>
        </html>
      </ClerkProvider>
  );
}
